# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Kushal Sharma
description:      'I work as Software developer at Flipkart in Bangalore.'
url:              http://kushal.xyz
baseurl:          /
logo:             /content/images/me.jpg

author:
  name:           'Kushal Sharma'
  url:            https://medium.com/@kushal.sharma

paginate:         5

disqus_shortname: kushalsharma

github:
  repo:           https://github.com/kushalsharma/kushal.github.io

gems:
  - jekyll-sitemap
  - jekyll-paginate

twitter: '@'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
  syntax_highlighter: rouge
